Module Utility
    Friend Const AbandonChangesText = "AbandonChanges"
    Friend Const CommitChangesText = "CommitChanges"
    Friend Const DeleteText = "Delete"
    Friend Const EditText = "Edit..."
    Friend Const EditLocationsText = "Edit Locations..."
    Friend Const GoBackText = "Go Back"
    Friend Const NewLocationText = "New Location"
    Friend Const NoText = "No"
    Friend Const QuitText = "Quit"
    Friend Const RenameText = "Rename"
    Friend Const ResetText = "Reset(Nuke World)"
    Friend Const YesText = "Yes"
    Friend Const BoilerplateDb = "boilerplate.db"
End Module
