Module Constants
    Friend Const AddChangeStatisticText = "Add/Change Statistic"
    Friend Const AddEquipSlotText = "Add Equip Slot"
    Friend Const BoilerplateDb = "boilerplate.db"
    Friend Const ChangeDisplayNameText = "Change Display Name"
    Friend Const ChangeNameText = "Change Name"
    Friend Const ChangeVergeTypeText = "Change Verge Type"
    Friend Const CharacterTypesText = "Character Types"
    Friend Const DeleteText = "Delete"
    Friend Const EquipSlotsText = "Equip Slots"
    Friend Const GoBackText = "Go Back"
    Friend Const ItemTypesText = "Item Types"
    Friend Const LocationsText = "Locations"
    Friend Const LocationTypesText = "Location Types"
    Friend Const NeverMindText = "Never Mind"
    Friend Const NewText = "New"
    Friend Const NoText = "No"
    Friend Const QuitText = "Quit"
    Friend Const RemoveEquipSlotText = "Remove Equip Slot"
    Friend Const RemoveStatisticText = "Remove Statistic"
    Friend Const RouteTypesText = "Route Types"
    Friend Const SaveAndQuitText = "Save and Quit"
    Friend Const StatisticTypesText = "Statistic Types"
    Friend Const VergesText = "Verges"
    Friend Const VergeTypesText = "Verge Types"
    Friend Const YesText = "Yes"
End Module
