Module Constants
    Friend Const AddChangeStatisticText = "Add/Change Statistic"
    Friend Const BoilerplateDb = "boilerplate.db"
    Friend Const ChangeDisplayNameText = "Change Display Name"
    Friend Const ChangeNameText = "Change Name"
    Friend Const CharacterTypesText = "Character Types"
    Friend Const DeleteText = "Delete"
    Friend Const GoBackText = "Go Back"
    Friend Const LocationTypesText = "Location Types"
    Friend Const NeverMindText = "Never Mind"
    Friend Const NewText = "New"
    Friend Const NoText = "No"
    Friend Const QuitText = "Quit"
    Friend Const RemoveStatisticText = "Remove Statistic"
    Friend Const SaveAndQuitText = "Save and Quit"
    Friend Const StatisticTypesText = "Statistic Types"
    Friend Const YesText = "Yes"
End Module
